const express = require('express');
const router = express.Router();
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const { authenticate } = require('../middleware/auth');
const crypto = require('crypto');
const logger = require('../utils/logger');

// Generate invite code
router.post('/generate', authenticate, async (req, res) => {
  try {
    const userId = req.user.userId;
    const { expiresInDays } = req.body;

    // Generate unique code
    const code = crypto.randomBytes(8).toString('hex').toUpperCase();

    // Calculate expiration
    let expiresAt = null;
    if (expiresInDays && expiresInDays > 0) {
      expiresAt = new Date();
      expiresAt.setDate(expiresAt.getDate() + expiresInDays);
    }

    const invite = await prisma.inviteCode.create({
      data: {
        code,
        createdBy: userId,
        expiresAt
      }
    });

    logger.info(`Invite code ${code} generated by user ${userId}`);
    res.json(invite);
  } catch (error) {
    logger.error('Error generating invite code:', error);
    res.status(500).json({ error: 'Failed to generate invite code' });
  }
});

// Get user's invite codes
router.get('/my-codes', authenticate, async (req, res) => {
  try {
    const userId = req.user.userId;

    const invites = await prisma.inviteCode.findMany({
      where: {
        createdBy: userId
      },
      include: {
        usedByUser: {
          select: {
            id: true,
            username: true,
            email: true
          }
        }
      },
      orderBy: {
        createdAt: 'desc'
      }
    });

    res.json(invites);
  } catch (error) {
    logger.error('Error fetching invite codes:', error);
    res.status(500).json({ error: 'Failed to fetch invite codes' });
  }
});

// Validate invite code
router.post('/validate', async (req, res) => {
  try {
    const { code } = req.body;

    if (!code) {
      return res.status(400).json({ error: 'Invite code is required' });
    }

    const invite = await prisma.inviteCode.findUnique({
      where: { code: code },
      include: {
        creator: {
          select: {
            id: true,
            username: true
          }
        }
      }
    });

    if (!invite) {
      return res.json({ valid: false, reason: 'Invalid code' });
    }

    if (invite.usedAt) {
      return res.json({ valid: false, reason: 'Code already used' });
    }

    if (invite.expiresAt && new Date() > invite.expiresAt) {
      return res.json({ valid: false, reason: 'Code expired' });
    }

    res.json({
      valid: true,
      creator: invite.creator,
      expiresAt: invite.expiresAt
    });
  } catch (error) {
    logger.error('Error validating invite code:', error);
    res.status(500).json({ error: 'Failed to validate invite code' });
  }
});

// Delete invite code
router.delete('/:inviteId', authenticate, async (req, res) => {
  try {
    const inviteId = parseInt(req.params.inviteId);
    const userId = req.user.userId;

    const invite = await prisma.inviteCode.findUnique({
      where: { id: inviteId }
    });

    if (!invite) {
      return res.status(404).json({ error: 'Invite code not found' });
    }

    if (invite.createdBy !== userId) {
      return res.status(403).json({ error: 'Not authorized to delete this invite' });
    }

    if (invite.usedAt) {
      return res.status(400).json({ error: 'Cannot delete used invite code' });
    }

    await prisma.inviteCode.delete({
      where: { id: inviteId }
    });

    logger.info(`Invite code ${inviteId} deleted by user ${userId}`);
    res.json({ message: 'Invite code deleted successfully' });
  } catch (error) {
    logger.error('Error deleting invite code:', error);
    res.status(500).json({ error: 'Failed to delete invite code' });
  }
});

// Get invite statistics
router.get('/stats', authenticate, async (req, res) => {
  try {
    const userId = req.user.userId;

    const totalInvites = await prisma.inviteCode.count({
      where: { createdBy: userId }
    });

    const usedInvites = await prisma.inviteCode.count({
      where: {
        createdBy: userId,
        usedAt: { not: null }
      }
    });

    const activeInvites = await prisma.inviteCode.count({
      where: {
        createdBy: userId,
        usedAt: null,
        OR: [
          { expiresAt: null },
          { expiresAt: { gt: new Date() } }
        ]
      }
    });

    const expiredInvites = await prisma.inviteCode.count({
      where: {
        createdBy: userId,
        usedAt: null,
        expiresAt: { lt: new Date() }
      }
    });

    res.json({
      total: totalInvites,
      used: usedInvites,
      active: activeInvites,
      expired: expiredInvites
    });
  } catch (error) {
    logger.error('Error fetching invite stats:', error);
    res.status(500).json({ error: 'Failed to fetch invite statistics' });
  }
});

module.exports = router;
